require("mini.icons").setup({
	lsp = {
		array = { glyph = "" },
		boolean = { glyph = "󰨙" },
		class = { glyph = "󰠱" },
		color = { glyph = "󰏘" },
		constant = { glyph = "󰏿" },
		constructor = { glyph = "" },
		copilot = { glyph = "" },
		enum = { glyph = "" },
		enummember = { glyph = "" },
		event = { glyph = "" },
		field = { glyph = "" },
		file = { glyph = "" },
		folder = { glyph = "" },
		["function"] = { glyph = "󰊕" },
		interface = { glyph = "" },
		key = { glyph = "󰻾" },
		keyword = { glyph = "" },
		method = { glyph = "󰊕" },
		module = { glyph = "" },
		namespace = { glyph = "󰦮" },
		null = { glyph = "" },
		number = { glyph = "󰎠" },
		object = { glyph = "" },
		operator = { glyph = "󰆕" },
		package = { glyph = "" },
		property = { glyph = "" },
		reference = { glyph = "" },
		snippet = { glyph = "󱄽" },
		string = { glyph = "" },
		struct = { glyph = "󰙅" },
		text = { glyph = "󰉿" },
		typeparameter = { glyph = "" },
		unit = { glyph = "󰳂" },
		value = { glyph = "󰦨" },
		variable = { glyph = "" },
	},
})
