local util = require("conform.util")

require("conform").setup({
	formatters = {
		["biome-check"] = {
			require_cwd = true,
			cwd = util.root_file({ "biome.json", "biome.jsonc" }),
		},
		deno_fmt = {
			require_cwd = true,
			cwd = util.root_file({ "deno.json", "deno.jsonc" }),
		},
		dprint = {
			require_cwd = true,
			cwd = util.root_file({ "dprint.json", "dprint.jsonc" }),
		},
		prettier = {
			require_cwd = true,
			cwd = util.root_file({
				"package.json",
				".prettierrc",
				".prettierrc.json",
				".prettierrc.yml",
				".prettierrc.yaml",
				".prettierrc.js",
				".prettierrc.mjs",
				".prettierrc.cjs",
				".prettierrc.toml",
				"prettier.config.js",
				"prettier.config.mjs",
				"prettier.config.cjs",
			}),
		},
		prettierd = {
			require_cwd = true,
			cwd = util.root_file({
				"package.json",
				".prettierrc",
				".prettierrc.json",
				".prettierrc.yml",
				".prettierrc.yaml",
				".prettierrc.js",
				".prettierrc.mjs",
				".prettierrc.cjs",
				".prettierrc.toml",
				"prettier.config.js",
				"prettier.config.mjs",
				"prettier.config.cjs",
			}),
		},
		rustfmt = {
			require_cwd = true,
			cwd = util.root_file({
				"Cargo.toml",
				"rustfmt.toml",
				".rustfmt.toml",
			}),
		},
	},
	formatters_by_ft = {
		astro = {
			"dprint",
			-- TODO: Add oxfmt once supported
			-- See <https://github.com/oxc-project/oxc/issues/19715>
			"biome-check",
			"prettierd",
			"prettier",
			lsp_format = "fallback",
			stop_after_first = true,
		},
		css = {
			"dprint",
			"oxfmt",
			"biome-check",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		c = { "clang-format" },
		cpp = { "clang-format" },
		go = { "gofmt" },
		html = {
			"dprint",
			"oxfmt",
			"biome-check",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		javascript = {
			"dprint",
			"oxfmt",
			"biome-check",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		javascriptreact = {
			"dprint",
			"oxfmt",
			"biome-check",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		json = {
			"dprint",
			"oxfmt",
			"biome-check",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		json5 = {
			"dprint",
			"oxfmt",
			"biome-check",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		jsonc = {
			"dprint",
			"oxfmt",
			"biome-check",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		lua = { "stylua" },
		markdown = {
			"dprint",
			"oxfmt",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		nix = { "nixfmt" },
		python = { "dprint", "ruff_format", stop_after_first = true },
		scss = {
			"dprint",
			"oxfmt",
		},
		svg = {
			"dprint",
			-- TODO: Add oxfmt once supported (Planned for oxfmt 1.0)
			-- See <https://github.com/oxc-project/oxc/issues/18035>
			"biome-check",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		toml = { "dprint", "oxfmt", lsp_format = "fallback", stop_after_first = true },
		typescript = {
			"dprint",
			"oxfmt",
			"biome-check",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		typescriptreact = {
			"dprint",
			"oxfmt",
			"biome-check",
			"prettierd",
			"prettier",
			"deno_fmt",
			stop_after_first = true,
		},
		yaml = { "dprint", "oxfmt", "prettierd", "prettier", stop_after_first = true },
	},
	format_on_save = {
		timeout_ms = 500,
		lsp_format = "fallback",
	},
})

vim.o.formatexpr = "v:lua.require('conform').formatexpr()"
